packages/epics/src/organisation/components/card-organisation.tsx

fix(CardOrganization): component props

---

apps/web/src/app/[lang]/page.tsx
packages/ui/src/atoms/logo/index.tsx
packages/ui/src/organisms/footer.tsx
packages/ui/src/organisms/index.ts

- Created new footer component and insert it in Dhos page

feat(Footer): created new footer component

---

apps/web/src/app/[lang]/page.tsx
package.json
packages/ui/src/carousel.tsx
packages/ui/src/index.ts
pnpm-lock.yaml

- Added new carousel component
- Added dhos carousel in dhos page

feat(Carousel): added carousel in dhos page

---

apps/web-e2e/src/example.spec.ts
apps/web/src/app/[lang]/my-spaces/layout.tsx
apps/web/src/app/[lang]/my-spaces/page.tsx
apps/web/src/app/[lang]/network/layout.tsx
apps/web/src/app/[lang]/network/page.tsx
apps/web/src/app/[lang]/page.tsx
apps/web/src/app/[lang]/wallet/layout.tsx
apps/web/src/app/[lang]/wallet/page.tsx
packages/epics/src/profile/components/button-profile.tsx
packages/ui/src/button-nav-item.tsx
packages/ui/src/organisms/menu-top.tsx

- Added new routes for Network, My Spaces, Wallet pages
- Redesigned MenuTop component
- Added MenuTop component in My Spaces page
- Redesigned few little components

feat(Header): dhos page header

---

package.json

start storybook by:
`pnpm run storybook`

chore: storybook command

---

packages/ui/src/molecules/badges-list.stories.tsx
packages/ui/src/molecules/badges-list.tsx

Create reusable bage list component

feat(TransactionsList #92): refactor badges list component

---

packages/epics/src/treasury/components/transactions/transaction-card.stories.tsx
packages/epics/src/treasury/components/transactions/transaction-card.tsx
packages/ui/src/index.ts

feat(TransactionsList #92): create transaction card component

---

apps/web/src/app/[lang]/dho/[id]/membership/page.tsx
packages/epics/src/membership/components/inner-spaces/inner-space-card.tsx
packages/epics/src/membership/components/inner-spaces/inner-spaces-section.tsx
packages/epics/src/membership/components/members/member-card.tsx
packages/epics/src/membership/components/members/members-section.tsx
packages/epics/src/membership/components/outer-spaces/outer-space-card.tsx
packages/epics/src/membership/components/outer-spaces/outer-spaces-section.tsx

- Membership epic styles fixing

fix(membership): membership epic styles fixing

---

apps/web/src/app/[lang]/dho/[id]/treasury/page.tsx
packages/epics/src/treasury/components/assets/asset-card.tsx
packages/epics/src/treasury/components/assets/assets-section.tsx
packages/epics/src/treasury/components/payouts/payout-card.tsx
packages/epics/src/treasury/components/requests/request-card.tsx
packages/epics/src/treasury/components/requests/requests-section.tsx

fix(treasury): treasury epic styles fixing

---

apps/web/src/app/[lang]/dho/[id]/agreements/page.tsx
apps/web/src/app/[lang]/dho/[id]/layout.tsx
apps/web/src/app/[lang]/dho/layout.tsx
apps/web/src/app/[lang]/dho/new/layout.tsx
apps/web/src/app/[lang]/my-spaces/layout.tsx
apps/web/src/app/[lang]/my-spaces/page.tsx
apps/web/src/app/[lang]/network/layout.tsx
apps/web/src/app/[lang]/wallet/layout.tsx
packages/epics/src/agreements/components/agreement-card.tsx
packages/epics/src/discussions/components/discussion-card.tsx
packages/epics/src/discussions/components/discussions-section.tsx
packages/epics/src/organisation/components/card-organisation.tsx
packages/epics/src/profile/components/button-profile.tsx
packages/epics/src/proposals/components/proposal-card.tsx
packages/epics/src/proposals/components/proposal-head.tsx
packages/epics/src/proposals/components/proposals-section.tsx
packages/ui/src/badge.tsx
packages/ui/src/card.tsx
packages/ui/src/container.tsx
packages/ui/src/molecules/badges-list.stories.tsx
packages/ui/src/molecules/badges-list.tsx
packages/ui/src/organisms/amount.tsx
packages/ui/src/organisms/menu-top.tsx
packages/ui/src/organisms/section-filter.tsx
packages/ui/src/organisms/section-tabs.tsx

- Agreements epic styles fixing

fix(agreements): agreements epic styles fixing

---

apps/web/src/app/[lang]/dho/[id]/layout.tsx
apps/web/src/app/[lang]/dho/layout.tsx
apps/web/src/app/[lang]/dho/new/layout.tsx
apps/web/src/app/[lang]/my-spaces/layout.tsx
apps/web/src/app/[lang]/network/layout.tsx
apps/web/src/app/[lang]/wallet/layout.tsx
packages/epics/src/organisation/components/card-organisation.tsx
packages/epics/src/profile/components/button-profile.tsx
packages/ui/src/badge.tsx
packages/ui/src/card.tsx
packages/ui/src/container.tsx
packages/ui/src/molecules/badges-list.stories.tsx
packages/ui/src/molecules/badges-list.tsx
packages/ui/src/organisms/amount.tsx
packages/ui/src/organisms/menu-top.tsx
packages/ui/src/organisms/section-filter.tsx
packages/ui/src/organisms/section-tabs.tsx

fix(components): ui components styles fixing

---

package.json
packages/epics/src/treasury/components/assets/asset-card.tsx
packages/epics/src/treasury/components/payouts/payout-card.stories.tsx
packages/epics/src/treasury/components/payouts/payout-card.tsx
packages/epics/src/treasury/components/transactions/transactions-list.stories.tsx
packages/epics/src/treasury/components/transactions/transactions-list.tsx
packages/ui/src/card.tsx
pnpm-lock.yaml

feat(TransactionsList #92): integrate static component

---

apps/web/src/app/[lang]/dho/[id]/@aside/(.)discussions/[slug]/page.tsx
apps/web/src/app/[lang]/dho/[id]/@aside/(.)membership/space/[slug]/loading.tsx
apps/web/src/app/[lang]/dho/[id]/@aside/(.)membership/space/[slug]/page.tsx
apps/web/src/app/[lang]/dho/[id]/membership/page.tsx
apps/web/src/app/[lang]/dho/[id]/membership/space/[slug]/page.tsx
packages/api/graphql/src/query/inner-spaces/detail.ts
packages/api/graphql/src/query/inner-spaces/index.ts
packages/api/graphql/src/query/inner-spaces/list.mock.ts
packages/api/graphql/src/query/inner-spaces/list.ts
packages/api/graphql/src/query/inner-spaces/types.ts
packages/api/graphql/src/rsc.ts
packages/epics/src/membership/components/index.ts
packages/epics/src/membership/components/inner-spaces/inner-spaces-list.tsx
packages/epics/src/membership/components/inner-spaces/inner-spaces-section.tsx
packages/epics/src/membership/components/subspace-detail/subspace-detail.tsx
packages/epics/src/membership/hooks/index.ts
packages/epics/src/membership/hooks/use-subspace-by-slug.ts
packages/epics/src/membership/hooks/use-subspace-details.ts
packages/epics/src/membership/index.ts

- Added subspace detail page for inner spaces
#198

feat(InnerSpace): added subspace detail page

---

packages/epics/src/agreements/components/agreements-list.tsx
packages/epics/src/discussions/components/discussion-list.tsx
packages/epics/src/membership/components/inner-spaces/inner-space-card.tsx
packages/epics/src/membership/components/inner-spaces/inner-spaces-list.tsx
packages/epics/src/membership/components/members/members-list.tsx
packages/epics/src/membership/components/outer-spaces/outer-spaces-list.tsx
packages/epics/src/proposals/components/proposal-list.tsx
packages/epics/src/treasury/components/assets/assets-list.tsx
packages/epics/src/treasury/components/payouts/payouts-list.tsx
packages/epics/src/treasury/components/requests/requests-list.tsx

fix(Props): key props in lists

---

apps/web/src/app/[lang]/dho/[id]/@aside/(.)membership/person/[slug]/loading.tsx
apps/web/src/app/[lang]/dho/[id]/@aside/(.)membership/person/[slug]/page.tsx
apps/web/src/app/[lang]/dho/[id]/membership/page.tsx
apps/web/src/app/[lang]/dho/[id]/membership/person/[slug]/page.tsx
packages/api/graphql/src/query/comments/types.ts
packages/api/graphql/src/query/members/detail.ts
packages/api/graphql/src/query/members/index.ts
packages/api/graphql/src/query/members/list.mock.ts
packages/api/graphql/src/query/members/list.ts
packages/api/graphql/src/query/members/types.ts
packages/api/graphql/src/query/proposals/types.ts
packages/api/graphql/src/rsc.ts
packages/epics/src/membership/components/inner-spaces/inner-space-card.tsx
packages/epics/src/membership/components/members/index.ts
packages/epics/src/membership/components/members/member-spaces.tsx
packages/epics/src/membership/components/members/members-list.tsx
packages/epics/src/membership/components/members/members-section.tsx
packages/epics/src/membership/hooks/index.ts
packages/epics/src/membership/hooks/use-member-by-slug.ts
packages/epics/src/treasury/components/payouts/payouts-list.tsx
packages/epics/src/treasury/components/requests/requests-list.tsx

- Created PersonDetail panel #61

feat(MemberDetails): created person detail panel

---

packages/epics/src/membership/components/outer-spaces/outer-spaces-list.tsx
packages/epics/src/membership/hooks/use-spaces.ts

make sure only two items per page are fetched:

fix(outer-space): page size

---

apps/web/src/app/[lang]/@aside/(.)my-spaces/create/loading.tsx
apps/web/src/app/[lang]/@aside/(.)my-spaces/create/page.tsx
apps/web/src/app/[lang]/@aside/[...catchAll]/page.tsx
apps/web/src/app/[lang]/@aside/_components/side-panel.tsx
apps/web/src/app/[lang]/@aside/default.tsx
apps/web/src/app/[lang]/layout.tsx
apps/web/src/app/[lang]/my-spaces/create/page.tsx
apps/web/src/app/[lang]/my-spaces/page.tsx

- Added side panel with create space form #59

feat(CreateSpace): added create space side panel

---

apps/web/src/app/[lang]/dho/[id]/@aside/(.)discussions/create/loading.tsx
apps/web/src/app/[lang]/dho/[id]/@aside/(.)discussions/create/page.tsx
apps/web/src/app/[lang]/dho/[id]/discussions/create/page.tsx
packages/epics/src/discussions/components/discussions-section.tsx

- Added create discussion side panel #81

feat(CreateDiscussion): added create discussion side panel

---

packages/epics/src/organisation/components/index.ts
packages/epics/src/organisation/components/search.stories.tsx
packages/epics/src/organisation/components/search.tsx

- Created search component #79

feat(Search): added new search component

---

.vscode/extensions.json

feat(#310): Setup recommended extentions

---

.github/workflows/deploy-preview.yml
packages/core/src/components/governance/errors.ts
packages/core/src/components/governance/index.ts
packages/core/src/components/governance/repository-postgres.ts
packages/core/src/components/governance/repository.ts
packages/core/src/components/governance/service.ts
packages/core/src/components/governance/types.ts
packages/core/src/components/space-config/repository-postgres.ts
packages/core/src/components/space-config/repository.ts
packages/core/src/components/space-config/types.ts
packages/core/src/components/space/repository-memory.ts
packages/core/src/components/space/repository-postgres.ts
packages/core/src/config/defaults.ts
packages/core/src/container/provider.ts
packages/core/src/container/tokens.ts
packages/storage-postgres/migrations/0004_narrow_ender_wiggin.sql
packages/storage-postgres/migrations/0005_generate-slug.sql
packages/storage-postgres/migrations/0006_peaceful_ricochet.sql
packages/storage-postgres/migrations/meta/0004_snapshot.json
packages/storage-postgres/migrations/meta/0005_snapshot.json
packages/storage-postgres/migrations/meta/0006_snapshot.json
packages/storage-postgres/migrations/meta/_journal.json
packages/storage-postgres/src/index.ts
packages/storage-postgres/src/schema/document.ts
packages/storage-postgres/src/schema/index.ts
packages/storage-postgres/src/schema/shared.ts

feat(#287): Governance Entities Interface

---

apps/web/src/app/[lang]/dho/[id]/layout.tsx
apps/web/src/app/[lang]/my-spaces/page.tsx
apps/web/src/app/[lang]/page.tsx
packages/epics/src/organisation/components/card-organisation.tsx
packages/epics/src/organisation/components/space-group-slider.tsx

- Added dumb UI elements in explore page #53

feat(ExplorePage): added explore page elements

---

apps/web/src/app/.well-known/jwks.json/route.ts
package.json
pnpm-lock.yaml

feat(#319): AuthenticationService

---

apps/web/src/app/[lang]/dho/[id]/@aside/(.)agreements/[slug]/page.tsx
apps/web/src/app/[lang]/dho/[id]/@aside/(.)discussions/[slug]/page.tsx
apps/web/src/app/[lang]/dho/[id]/@aside/(.)discussions/create/page.tsx
apps/web/src/app/[lang]/dho/[id]/@aside/(.)membership/person/[slug]/page.tsx
apps/web/src/app/[lang]/dho/[id]/@aside/(.)proposals/[slug]/page.tsx
apps/web/src/app/[lang]/dho/[id]/_components/navigation-tabs.tsx
apps/web/src/app/[lang]/dho/[id]/agreements/[slug]/page.tsx
apps/web/src/app/[lang]/dho/[id]/agreements/constants.ts
apps/web/src/app/[lang]/dho/[id]/constants.ts
apps/web/src/app/[lang]/dho/[id]/discussions/[slug]/page.tsx
apps/web/src/app/[lang]/dho/[id]/discussions/create/page.tsx
apps/web/src/app/[lang]/dho/[id]/layout.tsx
apps/web/src/app/[lang]/dho/[id]/membership/person/[slug]/page.tsx
apps/web/src/app/[lang]/dho/[id]/proposals/[slug]/page.tsx
apps/web/src/app/[lang]/my-spaces/page.tsx
apps/web/src/app/[lang]/page.tsx

feat(#321): use agreements path helper

---

.github/workflows/ci.yml
.github/workflows/deploy-preview.yml

feat(#344): Run ci only after deploy preview

---

packages/epics/src/profile/components/person-avatar.stories.tsx
packages/epics/src/profile/components/person-avatar.tsx
packages/ui/src/avatar.tsx

Improved UI for avatar fallback. Closes #380

feat(#380): design fallback avatar

---

.vscode/settings.json

feat(#423): Group related files in vscode

---

packages/storage-evm/project.json

feat(#391): rename build step

---

.vscode/vscode-git-graph.json

feat(#414): GitGraph Configuration

---

.github/workflows/deploy-preview.yml
.github/workflows/deploy-production.yml
nx.json
package.json
pnpm-lock.yaml

feat(#387): Setup vercel nx remote cache

---

.github/workflows/deploy-preview.yml
.github/workflows/deploy-production.yml
nx.json
package.json
pnpm-lock.yaml

feat(#387): remove vercel nx remote cache

---

README.md

feat(#413): add contributors to the README

---

apps/web/src/app/error.tsx
apps/web/src/app/global-error.tsx
apps/web/src/app/layout.tsx
apps/web/src/app/not-found.tsx

feat(#459): Fix Build issue missing pages

---

README.md
package.json
packages/storage-evm/.gitignore
packages/storage-evm/README.md
packages/storage-evm/project.json
packages/storage-evm/src/index.ts
packages/storage-evm/wagmi.config.ts
pnpm-lock.yaml
tsconfig.base.json

feat(#462): setup wagmi

---

.github/workflows/deploy-preview.yml

feat(#314): set branch db url for e2e step

---

.github/workflows/deploy-production.yml

feat(#505): Disable seed creation on main

---

apps/web/next.config.js

feat(#504): Allow additional domain for images

---

.github/workflows/deploy-production.yml

feat(#510): add upterm session on failure

---

.github/workflows/deploy-production.yml

feat(#510): add missing env variable

---

apps/web/src/hooks/use-me.ts

feat(#510): prevent permanent redirect

---

.github/workflows/deploy-production.yml
nx.json

feat(#510): add authenticated db url

---

packages/epics/src/agreements/components/agreement-detail.tsx
packages/epics/src/common/create-form/create-form.tsx
packages/epics/src/discussions/components/discussion-detail.tsx
packages/epics/src/discussions/components/discussion-list.tsx
packages/epics/src/membership/components/members/member-detail.tsx
packages/epics/src/membership/components/subspace-detail/subspace-detail.tsx
packages/epics/src/organisation/components/create-space-form.tsx
packages/epics/src/profile/components/edit-person-section.tsx
packages/epics/src/proposals/components/create-proposal-form.tsx
packages/epics/src/proposals/components/proposal-detail.tsx
packages/epics/src/treasury/components/assets/asset-detail.tsx
packages/epics/src/treasury/components/requests/request-form.tsx

- Fixed scroll issue for all back links #518

feat(#518): fixed scroll issue for all back links

---

apps/web/src/app/[lang]/dho/[id]/layout.tsx
apps/web/src/app/[lang]/my-spaces/page.tsx
packages/epics/src/organisation/components/card-organisation.tsx
packages/epics/src/organisation/components/card-organization.stories.tsx

- Added grid with 2 columns for My Spaces layout
- Added lead image for space card
#520

Feat/520-my spaces-grid

---

apps/web/src/app/[lang]/dho/[id]/@aside/(.)membership/person/[personSlug]/page.tsx
apps/web/src/hooks/use-spaces-by-member-slug.ts
packages/epics/src/membership/hooks/types.ts

feat(#535): Load spaces for member from api

---

apps/web/src/app/[lang]/@aside/_components/side-panel.tsx

- Fixed member side panel width #530

feat(#530): fixed member side panel width

---

apps/web/src/app/api/v1/people/me/route.ts

feat(#539): don't cache me endpoint

---

apps/web/src/app/api/v1/people/me/route.ts

chore: revalidate api/v1/people/me everytime

---

apps/web/src/app/[lang]/dho/[id]/layout.tsx
apps/web/src/app/[lang]/my-spaces/page.tsx
packages/epics/src/organisation/components/space-group-slider.tsx

feat(#503): Fix Image link issues across the app

---

apps/web/src/app/api/v1/people/me/[cacheBreaker]/route.ts
apps/web/src/hooks/use-me.ts

feat(#548): Cache breaker for /api/v1/people/me/<id> endpoint

---

packages/epics/src/organisation/components/card-organisation.tsx

- Added truncation for dao card description #551

feat(#551): added truncation for dao card description

---

packages/epics/src/agreements/components/agreement-card.tsx
packages/epics/src/proposals/components/proposal-head.tsx

- Fixed agreements card avatar size #529

feat(#529): fixed agreements avatar size

---

packages/epics/src/people/components/button-profile.tsx
packages/epics/src/people/components/person-avatar.tsx

- Fixed button profile loading state #604

feat(#604): fixed button profile loading state

---

apps/web/src/app/[lang]/dho/[id]/agreements/page.tsx
packages/epics/src/governance/components/document-section.tsx
packages/ui/src/organisms/section-load-more.tsx
packages/ui/src/organisms/section-tabs.tsx

fix(#595): layout fixes

---

packages/epics/src/agreements/components/agreement-head.stories.tsx
packages/epics/src/common/create-form/create-form-head.stories.tsx
packages/epics/src/common/create-form/create-form.stories.tsx
packages/epics/src/interactions/components/message.stories.tsx
packages/epics/src/people/components/edit-person-head.stories.tsx
packages/epics/src/people/components/edit-person-section.stories.tsx
packages/epics/src/proposals/components/create-proposal-form.stories.tsx
packages/epics/src/spaces/components/create-space-form-head.stories.tsx
packages/epics/src/spaces/components/create-space-form.stories.tsx
packages/epics/src/treasury/components/payouts/payout-card.stories.tsx
packages/epics/src/treasury/components/requests/request-card.stories.tsx
packages/epics/src/treasury/components/requests/request-form-head.stories.tsx
packages/epics/src/treasury/components/transactions/transaction-card.stories.tsx
packages/epics/src/treasury/components/transactions/transactions-list.stories.tsx
packages/ui/src/file-uploader.stories.tsx
packages/ui/src/molecules/badges-list.stories.tsx
packages/ui/src/molecules/markdown/markdown.stories.tsx
packages/ui/src/textarea.stories.tsx

Make sure to use Component as type definition.

fix: correct types in story objects
